job-template/job/ray_sklearn/README.md
job-template/job/xgb_train_and_predict/README.md

(docs)添加模板描述

---

myapp/views/view_notebook.py

disable jupyter notebook check `xsrf`

disable jupyter notebook check `xsrf`

---

install/docker/dockerFrontend/nginx.80.conf
install/kubernetes/cube/base/deploy-frontend.yaml
myapp/models/model_nni.py
myapp/models/model_notebook.py
myapp/project.py
myapp/views/home.py

support non-80 ports

---

myapp/forms.py
myapp/views/baseApi.py

add download args and retry pull info

add download args and retry pull info

---

README.md
README_CN.md

add more template doc

---

install/docker/README.md

optimize readme, add mysql grant, build kubeflow-dashboard:frontend-2022.08.01 image  and QA

Feature 1.0.0 optimize doc 20220823 hamawhite

---

images/jupyter-notebook/build.sh
images/jupyter-notebook/hadoop/Dockerfile-ubuntu-hadoop
images/jupyter-notebook/hadoop/examples/spark/pyspark_local.ipynb
images/jupyter-notebook/hadoop/examples/spark/pyspark_local_hive.ipynb
images/jupyter-notebook/hadoop/examples/spark/pyspark_yarn.ipynb
images/jupyter-notebook/hadoop/run-jupyter.sh
install/docker/README.md

Jupyter notebook image supports apache spark and comes with examples

Feature 1.0.0 jupyter spark 20220825 hamawhite

---

images/jupyter-notebook/build.sh
images/jupyter-notebook/hadoop/Dockerfile
images/jupyter-notebook/hadoop/Dockerfile-ubuntu-hadoop
images/jupyter-notebook/hadoop/conf/flink/flink-dep.xml
images/jupyter-notebook/hadoop/conf/hadoop/core-site.xml
images/jupyter-notebook/hadoop/conf/hadoop/hdfs-site.xml
images/jupyter-notebook/hadoop/conf/hadoop/yarn-site.xml
images/jupyter-notebook/hadoop/conf/hive/hive-site.xml
images/jupyter-notebook/hadoop/examples/flink/pyflink_sql.ipynb
images/jupyter-notebook/hadoop/examples/flink/pyflink_sql_hivecatalog.ipynb
images/jupyter-notebook/hadoop/maven/conf/settings.xml
images/jupyter-notebook/hadoop/run-jupyter.sh

Jupyter notebook image supports apache flink and  with examples

Jupyter notebook image supports apache flink and  with examples

---

install/kubernetes/juicefs/start_juicefs.sh

增加juicefs的二进制程序，并在脚本中增加相应的安装操作

---

install/docker/README.md

add front-end mirror description.

feat(install/docker):add front-end mirror description

---

images/jupyter-notebook/bigdata/examples/hive/remote-impyla.ipynb
images/jupyter-notebook/bigdata/examples/hive/remote-pyhive.ipynb

add hive and impyla examples to bigdata

feat(jupyter-notebook):add hive and impyla examples to bigdata

---

.gitignore
aihub/src/cubestudio/aihub/web/frontend/README.md
aihub/src/cubestudio/aihub/web/frontend/src/App.tsx
aihub/src/cubestudio/aihub/web/frontend/src/api/interface/baseInterface.ts
aihub/src/cubestudio/aihub/web/frontend/src/components/DynamicForm/DynamicForm.tsx
aihub/src/cubestudio/aihub/web/frontend/src/routerConfig.tsx

fix:fix Compilation exception

---

aihub/deep-learning/stable-diffusion-zh-en/Dockerfile
aihub/deep-learning/stable-diffusion-zh-en/app.py
aihub/deep-learning/stable-diffusion-zh-en/init.sh
aihub/deep-learning/stable-diffusion-zh-en/predictor.py

add SD CHINESE MODEL

---

aihub/deep-learning/cartoon-sd/Dockerfile
aihub/deep-learning/cartoon-sd/app.py
aihub/deep-learning/cartoon-sd/config.py
aihub/deep-learning/cartoon-sd/init.sh

add cartoon sd

---

aihub/deep-learning/cartoon-sd/app.py
aihub/src/cubestudio/aihub/web/server.py

update cartoon-sd and give aihub server debug choose

update cartoon-sd and give aihub server debug choose

---

aihub/deep-learning/cartoon-sd/app.py

 add img_2_img

---

install/kubernetes/readme.md

按照此文档下面的视频，里面写得兼容得版本k8s v1.18.20

Update readme.md 增加k8s版本兼容到v1.18.20

---

install/kubernetes/efk/kibana-all.yaml
install/kubernetes/minio/cluster/minio-distributed-statefulset.yaml
install/kubernetes/minio/minio-mc.yaml
install/kubernetes/minio/single/minio-single-statefulset.yaml

fix部署kibana minio部署节点到amd64节点到亲和性

add amd64机器亲和性

---

install/docker/config.py
install/kubernetes/cube/overlays/config/config.py

fix image type

---

myapp/frontend/src/pages/IframeTemplate.tsx

fixed drag bar overlap
